[package]
name = "bus-mapping"
version = "0.1.0"
edition = "2018"
authors = ["CPerezz <c.perezbaro@gmail.com>"]


[dependencies]
ff = "0.11"
pasta_curves = "0.1"
itertools = "0.10"
serde = {version = "1.0.130", features = ["derive"] }
lazy_static = "1.4"
serde_json = "1.0.66"
hex = "0.4"
geth-utils = { path = "../geth-utils" }
web3 = {version = "0.17", default-features = false}
uint = "0.9.1"
ethers-providers = "0.5.5"
regex = "1.5.4"

[dev-dependencies]
url = "2.2.2"
tokio = { version = "1.13", features = ["macros"] }
pretty_assertions = "1.0.0"
